### ISSUE TITLE
User is unable to see the paragraph in mobile devices when user tries to type in textbox

### ISSUE THREAD

**Issue by mrinmay7875** [mrinmay7875/react_typing_app#1]
Currently when user opens the app in Mobile devices then tries to type in the textbox then user is scrolled down at the textbox and hence user is not able to see the words in order to type.

This makes the app almost unusable in mobile devices. However in desktop screen this issue does not occur and user can use it without any issue.

**Comment by mowabanga** [comment]
Hi mrinmay7875, I would like to work on this issue if it still remains unresolved.

**Comment by mrinmay7875** [comment]
This issue has been fixed with https://github.com/mrinmay7875/react_typing_app/commit/440248d5b40c66053ce649ee6dede27df0baddb0 and https://github.com/mrinmay7875/react_typing_app/commit/df94cd9d7e4131eea11294447467ebb073688aee

Here is how it looks on mobile devices. Closing this issue.
![IMG_20230826_224521](https://github.com/mrinmay7875/react_typing_app/assets/33797909/0ee463f3-de56-4551-93c1-a779175d9e28)
