### ISSUE TITLE
Timer is not visible properly in Mobile screen.

### ISSUE THREAD

**Issue by mrinmay7875** [mrinmay7875/react_typing_app#9]
In Mobile user is not able to see the timer properly because it is overlapping with the App header. If anyone wants to work on this issue, please feel free to start.

Here is how it looks on mobile screen. This issue is only happening in Mobile screen. In desktop screen it is working fine.
![IMG_20230831_230918](https://github.com/mrinmay7875/react_typing_app/assets/33797909/dc296077-9787-4b41-9b23-a0d1afd994fc)

**Comment by ivanosquis10** [comment]
Can I take the issue?

**Comment by mrinmay7875** [comment]
@ivanosquis10 Sure, go ahead

**Comment by mrinmay7875** [comment]
This issue has been fixed with #10. Closing the issue.
